/*
========================================================================================
    PROCESS: MULTIQC
    Tool   : MultiQC v1.19+
    Purpose: Aggregate QC reports from FastQC, Trim Galore, STAR, featureCounts
========================================================================================
*/

process MULTIQC {
    label 'process_single'

    publishDir "${params.outdir}/multiqc", mode: 'copy'

    input:
    path  multiqc_files, stageAs: "?/*"   // collect all QC outputs
    path  multiqc_config                  // optional config YAML (may be empty)

    output:
    path "*multiqc_report.html",  emit: report
    path "*_data",                emit: data
    path "*_plots",               emit: plots, optional: true
    path "versions.yml",          emit: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def config_arg  = multiqc_config ? "--config ${multiqc_config}" : ''
    def extra_args  = task.ext.args ?: ''
    """
    multiqc \\
        --force \\
        --outdir . \\
        --filename rnaseq_multiqc_report \\
        --title "RNAseq Pipeline QC Report" \\
        --comment "Generated by rnaseq-pipeline v2.0" \\
        ${config_arg} \\
        ${extra_args} \\
        .

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        multiqc: \$( multiqc --version | sed 's/multiqc, version //' )
    END_VERSIONS
    """

    stub:
    """
    touch rnaseq_multiqc_report.html
    mkdir -p rnaseq_multiqc_report_data
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        multiqc: 1.19
    END_VERSIONS
    """
}
